### ISSUE TITLE
Expand-Archive does not return a System.IO.FileInfo nor System.IO.DirectoryInfo

### ISSUE THREAD

**Issue by inwenis** [PowerShell/Microsoft.PowerShell.Archive#38] opened 2017-06-26 20:39 UTC
The docs (https://msdn.microsoft.com/en-us/powershell/reference/5.1/microsoft.powershell.archive/expand-archive) say that Expand-Archive should return a System.IO.FileInfo or System.IO.DirectoryInfo but it has no output

**Comment by sdwheeler** [comment] 2019-10-22 21:34
This was fixed in MicrosoftDocs/PowerShell-Docs#3696 on Feb 12. You need to run Update-Help -Force to get the new help files.

**Comment by sdwheeler** [comment] 2019-10-22 22:05
This is a duplicate of issue #9.

**Closed** 2022-06-01 21:50 UTC
