### ISSUE TITLE
Expand-Archive and Compress-Archive do not support paths containing PSDrives

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/Microsoft.PowerShell.Archive#3] opened 2016-04-20 16:47 UTC
Filed by @KirkMunro [on UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/13246845-microsoft-powershell-archive-cmdlets-expand-archi) (emphasis mine):

"The Expand-Archive and Compress-Archive cmdlets in the Microsoft.PowerShell.Archive module each have several parameters that take in a file system path. These parameters currently only support standard file system paths (behind a drive letter or a UNC share) and not PowerShell FileSystem paths which may include a custom PowerShell drive (e.g. Documents:\myfile.zip). **This support is easy to implement and should be added (I'd add it myself if this module was open source, which it should be)**.

The workaround is to explicitly use standard file system paths, either via the Resolve-Path cmdlet or by using them verbatim in your command invocation."

Obviously, I'd love for you to help out here, Kirk. ;)

**Comment by KirkMunro** [comment] 2016-04-20 17:10
You bet, I have it in my queue.  Just buried under a few critical tasks at the moment.  Maybe tomorrow evening or Friday.

**Comment by oising** [comment] 2016-04-20 23:57
I wrote a skeleton some years ago in response to a query on StackOverflow, Kirk, that you could pretty much take verbatim. It covers wildcards/globbing, enforcing the pspath resolves to a provider path in the filesystem provider and a few other things. It should be pretty solid.

http://stackoverflow.com/questions/8505294/how-do-i-deal-with-paths-when-writing-a-powershell-cmdlet/8506768#8506768

```
using System;
using System.Collections.Generic;
using System.IO;
using System.Management.Automation;
using Microsoft.PowerShell.Commands;
namespace PSQuickStart
{
    [Cmdlet(VerbsCommon.Get, Noun,
        DefaultParameterSetName = ParmamSetPath,
        SupportsShouldProcess = true)
    ]
    public class GetFileMetadataCommand : PSCmdlet
    {
        private const string Noun = "FileMetadata";
        private const string ParamSetLiteral = "Literal";
        private const string ParmamSetPath = "Path";
        private string[] _paths;
        private bool _shouldExpandWildcards;
        [Parameter(
            Position = 0,
            Mandatory = true,
            ValueFromPipeline = false,
            ValueFromPipelineByPropertyName = true,
            ParameterSetName = ParamSetLiteral)
        ]
        [Alias("PSPath")]
        [ValidateNotNullOrEmpty]
        public string[] LiteralPath
        {
            get { return _paths; }
            set { _paths = value; }
        }
        [Parameter(
            Position = 0,
            Mandatory = true,
            ValueFromPipeline = true,
            ValueFromPipelineByPropertyName = true,
            ParameterSetName = ParmamSetPath)
        ]
        [ValidateNotNullOrEmpty]
        public string[] Path
        {
            get { return _paths; }
            set
            {
                _shouldExpandWildcards = true;
                _paths = value;
            }
        }
        protected override void ProcessRecord()
        {
            foreach (string path in _paths)
            {
                // This will hold information about the provider containing
                // the items that this path string might resolve to.                
                ProviderInfo provider;
                // This will be used by the method that processes literal paths
                PSDriveInfo drive;
                // this contains the paths to process for this iteration of the
                // loop to resolve and optionally expand wildcards.
                List<string> filePaths = new List<string>();
                if (_shouldExpandWildcards)
                {
                    // Turn *.txt into foo.txt,foo2.txt etc.
                    // if path is just "foo.txt," it will return unchanged.
                    filePaths.AddRange(this.GetResolvedProviderPathFromPSPath(path, out provider));
                }
                else
                {
                    // no wildcards, so don't try to expand any * or ? symbols.                    
                    filePaths.Add(this.SessionState.Path.GetUnresolvedProviderPathFromPSPath(
                        path, out provider, out drive));
                }
                // ensure that this path (or set of paths after wildcard expansion)
                // is on the filesystem. A wildcard can never expand to span multiple
                // providers.
                if (IsFileSystemPath(provider, path) == false)
                {
                    // no, so skip to next path in _paths.
                    continue;
                }
                // at this point, we have a list of paths on the filesystem.
                foreach (string filePath in filePaths)
                {
                    PSObject custom;
                    // If -whatif was supplied, do not perform the actions
                    // inside this "if" statement; only show the message.
                    //
                    // This block also supports the -confirm switch, where
                    // you will be asked if you want to perform the action
                    // "get metadata" on target: foo.txt
                    if (ShouldProcess(filePath, "Get Metadata"))
                    {
                        if (Directory.Exists(filePath))
                        {
                            custom = GetDirectoryCustomObject(new DirectoryInfo(filePath));
                        }
                        else
                        {
                            custom = GetFileCustomObject(new FileInfo(filePath));
                        }
                        WriteObject(custom);
                    }
                }
            }
        }
        private PSObject GetFileCustomObject(FileInfo file)
        {
            // this message will be shown if the -verbose switch is given
            WriteVerbose("GetFileCustomObject " + file);
            // create a custom object with a few properties
            PSObject custom = new PSObject();
            custom.Properties.Add(new PSNoteProperty("Size", file.Length));
            custom.Properties.Add(new PSNoteProperty("Name", file.Name));
            custom.Properties.Add(new PSNoteProperty("Extension", file.Extension));
            return custom;
        }
        private PSObject GetDirectoryCustomObject(DirectoryInfo dir)
        {
            // this message will be shown if the -verbose switch is given
            WriteVerbose("GetDirectoryCustomObject " + dir);
            // create a custom object with a few properties
            PSObject custom = new PSObject();
            int files = dir.GetFiles().Length;
            int subdirs = dir.GetDirectories().Length;
            custom.Properties.Add(new PSNoteProperty("Files", files));
            custom.Properties.Add(new PSNoteProperty("Subdirectories", subdirs));
            custom.Properties.Add(new PSNoteProperty("Name", dir.Name));
            return custom;
        }
        private bool IsFileSystemPath(ProviderInfo provider, string path)
        {
            bool isFileSystem = true;
            // check that this provider is the filesystem
            if (provider.ImplementingType != typeof(FileSystemProvider))
            {
                // create a .NET exception wrapping our error text
                ArgumentException ex = new ArgumentException(path +
                    " does not resolve to a path on the FileSystem provider.");
                // wrap this in a powershell errorrecord
                ErrorRecord error = new ErrorRecord(ex, "InvalidProvider",
                    ErrorCategory.InvalidArgument, path);
                // write a non-terminating error to pipeline
                this.WriteError(error);
                // tell our caller that the item was not on the filesystem
                isFileSystem = false;
            }
            return isFileSystem;
        }
    }
}
```

**Comment by KirkMunro** [comment] 2016-04-21 09:54
That's super helpful, thanks @oising!

**Comment by KirkMunro** [comment] 2016-04-21 23:48
@joeyaiello it looks like this issue was already fixed before the module was published as open source?

**Comment by KirkMunro** [comment] 2016-04-25 12:17
I'm the OP who logged this issue, but right now I cannot reproduce it on my main system.  I'm going to test one other system (the one where I think I may have encountered this issue) to see if it's reproducible there, and if not I'll close this because it appears to work fine with PowerShell 5.0.10586.122 and the code to make this work seems solid.  It could be that the other system where I think I encountered this was running an older version.

**Comment by KirkMunro** [comment] 2016-10-07 23:57
I finally reproduced this issue again, with Compress-Archive when using a path containing a PS drive in the DestinationPath parameter.  Glad I wasn't losing my head before when I logged it.  Will fix.

**Closed** 2016-10-10 16:47 UTC
Labels: enhancement, help wanted

**Comment by oising** [comment] 2016-10-18 14:16
There needs to be guidance to ensure that cmdlets using `Path` / `LiteralPath` imply psdrives, not win32 paths. `FilePath` has precedence for the latter.
