### ISSUE TITLE
Support for password protected archive files.

### ISSUE THREAD

**Issue by TerryED0618** [PowerShell/Microsoft.PowerShell.Archive#132] opened 2022-07-22 13:39 UTC
### Summary of the new feature / enhancement

One business use of ZIP files is to encapsulate a set of file to be attached in an email.  Depending on the file contents, the attached ZIP may be blocked.  Password protecting the ZIP prevents antivirus scanners from examining the file contents and may be the only way to send some files across organization message hygiene solutions.

  Though this does open one opportunity for malware distribution, the password prompt should be sufficient pause for the user to consider the value versus risk of opening ZIP file.  

### Proposed technical implementation details (optional)

.NET will need to support password protected archive files when opening and when creating.

**Comment by SydneyhSmith** [comment] 2022-07-25 17:34
Thanks @TerryED0618 looks like a duplicate of #5 and #7

**Closed** 2022-08-01 20:51 UTC
Labels: duplicate
